spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/moviecollection
    username: postgres
    password: postgresPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  #hot reload for thymeleaf
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0