CREATE TABLE IF NOT EXISTS user_role (
    id INTEGER PRIMARY KEY,
    role_name VARCHAR
);

CREATE TABLE IF NOT EXISTS user_with_role(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id INTEGER REFERENCES users ON DELETE CASCADE,
    role_id INTEGER REFERENCES user_role
);